# Default language for the plugin.
# This determines the language used for messages and configurations.
# Supported values: "en" (English), "es" (Spanish), or other supported languages.
language: "en"

# Configuration for skills in the plugin.
# Each skill has its own settings for base XP, progression multiplier, and XP per action.
skill:

  # Agility skill configuration.
  # - base-xp: The base amount of XP required to level up.
  # - progression: The multiplier applied to the XP required for each subsequent level.
  # - xp-per-action: The amount of XP gained per action related to this skill.
  agility:
    base-xp: 100
    progression: 1.4
    xp-per-action: 0.2

  # Alchemy skill configuration.
  alchemy:
    base-xp: 100
    progression: 1.4
    xp-per-action: 10

  # Archery skill configuration.
  archery:
    base-xp: 100
    progression: 1.4
    xp-per-action: 5

  # Combat skill configuration.
  combat:
    base-xp: 100
    progression: 1.4
    xp-per-action: 20

  # Enchanting skill configuration.
  enchanting:
    base-xp: 100
    progression: 1.4
    xp-per-action: 15

  # Farming skill configuration.
  farming:
    base-xp: 100
    progression: 1.4
    xp-per-action: 5

  # Fishing skill configuration.
  fishing:
    base-xp: 100
    progression: 1.4
    xp-per-action: 15

  # Foraging skill configuration.
  foraging:
    base-xp: 100
    progression: 1.4
    xp-per-action: 4

  # Mining skill configuration.
  # - xp-per-action: XP gained for mining specific ores.
  mining:
    base-xp: 100
    progression: 1.4
    xp-per-action:
      COAL_ORE: 2
      COPPER_ORE: 3
      IRON_ORE: 4
      LAPIS_ORE: 5
      REDSTONE_ORE: 5
      GOLD_ORE: 6
      EMERALD_ORE: 8
      DIAMOND_ORE: 10

  # Smithing skill configuration.
  smithing:
    base-xp: 100
    progression: 1.4
    xp-per-action: 20